# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-27 15:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SatelliteImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aws_bucket_uri', models.TextField()),
                ('clouds_percentage', models.FloatField()),
                ('data_percentage', models.FloatField()),
                ('date', models.DateField()),
            ],
        ),
    ]
