# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-04 01:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='satelliteimage',
            name='source',
            field=models.TextField(default='L8'),
        ),
    ]
