AWS_ACCESS_KEY_ID = "AKIAITINGFWHLM4UH6EQ"
AWS_SECRET_ACCESS_KEY = "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"
GEOSERVER_USERNAME = "admin"
GEOSERVER_PASSWORD = "DaleCooper"
DATA_ROOT = '/home/piotrek/mgr/datasets/'